import Head from 'next/head'
import Image from 'next/image'
import styles from 'styles/Home.module.css'
import { MdKeyboardArrowDown } from 'react-icons/md';
import WhoIAm from 'components/whoiam';
import WhatDoIknow from 'components/knowledge';
import Projects from 'components/projects';
import { useState } from 'react';




export default function Home()  {
  const [showWhoIAm, setShowWhoIAm] = useState(true); 
  const [showWhatIknow, setShowWhatIknow] = useState({
    isHidden:true,
    display:'none',
  });
  const [showProyect, setShowProject] = useState({
    isHidden:true,
    display:'none',
  });

  const handleClick = (e:any, button:string) => {
    e.preventDefault()
    console.log(button)
    switch(button){
      case "whoIAm":
        showWhoIAm ? setShowWhoIAm(false) : setShowWhoIAm(true);
        break;
      case "WhatIKnow":
        showWhatIknow.isHidden ? setShowWhatIknow({
            isHidden: false, display:'flex'
          }) : setShowWhatIknow({
            isHidden:true, display:'none'
        });
        break;
      case "Proyect":
        showProyect.isHidden ? setShowProject({
          isHidden: false, display:'flex'
          }) : setShowProject({
            isHidden:true, display:'none'
        });

    }
    
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Presentation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
            integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
            crossOrigin="anonymous"
          />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hi, my name is David!
        </h1>

        <p className={styles.description}>
          <code className={styles.code}>And I&apos;am dominican developer.</code>
        </p>
        <div className={styles.information_titles} >
           <a onClick={(e) => handleClick(e, "whoIAm")}><h2>About Me <MdKeyboardArrowDown/></h2></a>
             <WhoIAm isHidden={ showWhoIAm }/>
            <a onClick={(e) => handleClick(e, "WhatIKnow")}><h2> What do I know? <MdKeyboardArrowDown/></h2></a>
              <WhatDoIknow isHidden={ showWhatIknow.isHidden } display={showWhatIknow.display}/>
            <a onClick={(e) => handleClick(e, "Proyect")}> <h2>¡My Projects! <MdKeyboardArrowDown/></h2></a>
              <Projects isHidden={showProyect.isHidden} display={showProyect.display}/>
        </div>

        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}




