import Head from 'next/head'
import Image from 'next/image'
import styles from 'styles/Home.module.css'
import { MdKeyboardArrowDown } from 'react-icons/md';
import { useState } from 'react';
import WhoIAm from './whoiam';
//ChakraUI
import { Container, Flex, VStack } from '@chakra-ui/react';



export default function Home()  {


  
  return (
    <>
      <Head>
        <title> David Rosario - Who I Am? </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <WhoIAm/>
      </main>
      
    </>
  )
}




